// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhOvWHFyKjOvt2rCWyMlxT8iIZGmr6oXk',
    appId: '1:154022289536:web:73d8828867c51a7e52c665',
    messagingSenderId: '154022289536',
    projectId: 'device-streaming-572d50a2',
    authDomain: 'device-streaming-572d50a2.firebaseapp.com',
    storageBucket: 'device-streaming-572d50a2.firebasestorage.app',
    measurementId: 'G-KSG9QEDTRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwNpljRm6XD61cPX10hkttoLpNW1WykM',
    appId: '1:154022289536:android:b3bf5a6b9ca37f5e52c665',
    messagingSenderId: '154022289536',
    projectId: 'device-streaming-572d50a2',
    storageBucket: 'device-streaming-572d50a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbf7FWl5bnFFyNfCvrVS5Fw8jGyUMkx4',
    appId: '1:154022289536:ios:8128cfa724d658d252c665',
    messagingSenderId: '154022289536',
    projectId: 'device-streaming-572d50a2',
    storageBucket: 'device-streaming-572d50a2.firebasestorage.app',
    androidClientId: '154022289536-4jkkb7l87ev1de219devh1k29gkuejr8.apps.googleusercontent.com',
    iosClientId: '154022289536-v1c77ti9qhr9i012bmvci7r1g5idlgkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitsyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbf7FWl5bnFFyNfCvrVS5Fw8jGyUMkx4',
    appId: '1:154022289536:ios:8128cfa724d658d252c665',
    messagingSenderId: '154022289536',
    projectId: 'device-streaming-572d50a2',
    storageBucket: 'device-streaming-572d50a2.firebasestorage.app',
    androidClientId: '154022289536-4jkkb7l87ev1de219devh1k29gkuejr8.apps.googleusercontent.com',
    iosClientId: '154022289536-v1c77ti9qhr9i012bmvci7r1g5idlgkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitsyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhOvWHFyKjOvt2rCWyMlxT8iIZGmr6oXk',
    appId: '1:154022289536:web:6899647bb34b416352c665',
    messagingSenderId: '154022289536',
    projectId: 'device-streaming-572d50a2',
    authDomain: 'device-streaming-572d50a2.firebaseapp.com',
    storageBucket: 'device-streaming-572d50a2.firebasestorage.app',
    measurementId: 'G-29MC8DEW9X',
  );

}