import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
// Note: This file will be generated by flutterfire configure
import 'firebase_options.dart';

import 'src/core/theme/premium_theme.dart';
import 'src/features/dashboard/dashboard_screen.dart';
import 'src/features/onboarding/screens/onboarding_screen.dart';
import 'src/features/auth/widgets/auth_wrapper.dart';
import 'src/features/auth/screens/login_screen.dart';
import 'src/features/auth/screens/signup_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Try to initialize Firebase
  // If firebase_options.dart is missing (not run yet), this might fail in a real build
  // but we assume the user will run the configure command.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Fallback for development if config is missing, though Auth won't work
    debugPrint('Firebase initialization failed: $e');
  }

  runApp(const ProviderScope(child: FitSyncApp()));
}

class FitSyncApp extends StatelessWidget {
  const FitSyncApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FitSync',
      theme: PremiumTheme.darkTheme,
      home: const AuthWrapper(),
      routes: {
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/onboarding': (context) => const OnboardingScreen(),
        '/dashboard': (context) => const DashboardScreen(),
      },
    );
  }
}
